name: Build and Deploy to Minikube

env:
  IMAGE: ghcr.io/eric12110/hello-service
  
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t hello-service:latest .

    - name: Setup Minikube Docker environment
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/docker-env.sh
        source docker-env.sh
      shell: bash

    - name: Load image into Minikube
      run: |
        minikube image load hello-service:latest

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/hello-deployment.yaml
